apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ include "tian-shu.namespace" . }}
  labels:
    {{- include "tian-shu.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
  selector:
    {{- include "tian-shu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
