-- Source: postgresql://postgres:postgres@localhost:5432/tianshu  Schema: tianshu
-- Generated by temp/dump_seed.py

-- ===== tianshu.agents =====
CREATE TABLE tianshu.agents (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    config json NOT NULL,
    soul text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, name)
);

-- ===== tianshu.alembic_version =====
CREATE TABLE tianshu.alembic_version (
    version_num varchar(32) NOT NULL,
    PRIMARY KEY (version_num)
);

-- ===== tianshu.channel_connections =====
CREATE TABLE tianshu.channel_connections (
    id varchar(64) NOT NULL,
    owner_user_id varchar(64) NOT NULL,
    provider varchar(32) NOT NULL,
    status varchar(32) NOT NULL,
    external_account_id varchar(128) NOT NULL,
    external_account_name varchar(256),
    workspace_id varchar(128) NOT NULL,
    workspace_name varchar(256),
    bot_user_id varchar(128),
    scopes_json json NOT NULL,
    capabilities_json json NOT NULL,
    metadata_json json NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    last_seen_at timestamptz,
    last_error_at timestamptz,
    PRIMARY KEY (id),
    UNIQUE (owner_user_id, provider, external_account_id, workspace_id),
    UNIQUE (provider, external_account_id, workspace_id)
);

-- ===== tianshu.channel_conversations =====
CREATE TABLE tianshu.channel_conversations (
    id varchar(64) NOT NULL,
    connection_id varchar(64) NOT NULL,
    owner_user_id varchar(64) NOT NULL,
    provider varchar(32) NOT NULL,
    external_conversation_id varchar(128) NOT NULL,
    external_topic_id varchar(128) NOT NULL,
    thread_id varchar(64) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (connection_id, external_conversation_id, external_topic_id),
    FOREIGN KEY (connection_id) REFERENCES tianshu.channel_conversations(id) ON DELETE CASCADE
);

-- ===== tianshu.channel_credentials =====
CREATE TABLE tianshu.channel_credentials (
    connection_id varchar(64) NOT NULL,
    encrypted_access_token text,
    encrypted_refresh_token text,
    token_type varchar(32),
    expires_at timestamptz,
    refresh_expires_at timestamptz,
    encrypted_extra_json text,
    version numeric(32,0) NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (connection_id),
    FOREIGN KEY (connection_id) REFERENCES tianshu.channel_credentials(id) ON DELETE CASCADE
);

-- ===== tianshu.channel_oauth_states =====
CREATE TABLE tianshu.channel_oauth_states (
    state_hash varchar(128) NOT NULL,
    owner_user_id varchar(64) NOT NULL,
    provider varchar(32) NOT NULL,
    code_verifier_encrypted text,
    nonce_hash varchar(128),
    redirect_after text,
    requested_scopes_json json NOT NULL,
    metadata_json json NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (state_hash)
);

-- ===== tianshu.checkpoint_blobs =====
CREATE TABLE tianshu.checkpoint_blobs (
    thread_id text NOT NULL,
    checkpoint_ns text NOT NULL DEFAULT ''::text,
    channel text NOT NULL,
    version text NOT NULL,
    type text NOT NULL,
    blob bytea,
    PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);

-- ===== tianshu.checkpoint_migrations =====
CREATE TABLE tianshu.checkpoint_migrations (
    v numeric(32,0) NOT NULL,
    PRIMARY KEY (v)
);

-- ===== tianshu.checkpoint_writes =====
CREATE TABLE tianshu.checkpoint_writes (
    thread_id text NOT NULL,
    checkpoint_ns text NOT NULL DEFAULT ''::text,
    checkpoint_id text NOT NULL,
    task_id text NOT NULL,
    idx numeric(32,0) NOT NULL,
    channel text NOT NULL,
    type text,
    blob bytea NOT NULL,
    task_path text NOT NULL DEFAULT ''::text,
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);

-- ===== tianshu.checkpoints =====
CREATE TABLE tianshu.checkpoints (
    thread_id text NOT NULL,
    checkpoint_ns text NOT NULL DEFAULT ''::text,
    checkpoint_id text NOT NULL,
    parent_checkpoint_id text,
    type text,
    checkpoint jsonb NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);

-- ===== tianshu.feedback =====
CREATE TABLE tianshu.feedback (
    feedback_id varchar(64) NOT NULL,
    run_id varchar(64) NOT NULL,
    thread_id varchar(64) NOT NULL,
    user_id varchar(64),
    message_id varchar(64),
    rating numeric(32,0) NOT NULL,
    comment text,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (feedback_id),
    UNIQUE (thread_id, run_id, user_id)
);

-- ===== tianshu.run_events =====
CREATE TABLE tianshu.run_events (
    id numeric(32,0) NOT NULL DEFAULT nextval('tianshu.run_events_id_seq'::regclass),
    thread_id varchar(64) NOT NULL,
    run_id varchar(64) NOT NULL,
    user_id varchar(64),
    event_type varchar(32) NOT NULL,
    category varchar(16) NOT NULL,
    content text NOT NULL,
    event_metadata json NOT NULL,
    seq numeric(32,0) NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (thread_id, seq)
);

-- ===== tianshu.runs =====
CREATE TABLE tianshu.runs (
    run_id varchar(64) NOT NULL,
    thread_id varchar(64) NOT NULL,
    assistant_id varchar(128),
    user_id varchar(64),
    status varchar(20) NOT NULL,
    operation_kind varchar(32) NOT NULL DEFAULT 'run'::character varying,
    model_name varchar(128),
    multitask_strategy varchar(20) NOT NULL,
    metadata_json json NOT NULL,
    kwargs_json json NOT NULL,
    error text,
    stop_reason varchar(50),
    message_count numeric(32,0) NOT NULL,
    first_human_message text,
    last_ai_message text,
    total_input_tokens numeric(32,0) NOT NULL,
    total_output_tokens numeric(32,0) NOT NULL,
    total_tokens numeric(32,0) NOT NULL,
    llm_call_count numeric(32,0) NOT NULL,
    lead_agent_tokens numeric(32,0) NOT NULL,
    subagent_tokens numeric(32,0) NOT NULL,
    middleware_tokens numeric(32,0) NOT NULL,
    token_usage_by_model json NOT NULL DEFAULT '{}'::json,
    follow_up_to_run_id varchar(64),
    owner_worker_id varchar(128),
    lease_expires_at timestamptz,
    cancel_action varchar(20),
    cancel_requested_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (run_id),
    UNIQUE (thread_id)
);

-- ===== tianshu.scheduled_task_runs =====
CREATE TABLE tianshu.scheduled_task_runs (
    id varchar(64) NOT NULL,
    task_id varchar(64) NOT NULL,
    thread_id varchar(64) NOT NULL,
    run_id varchar(64),
    scheduled_for timestamptz NOT NULL,
    trigger varchar(16) NOT NULL,
    status varchar(16) NOT NULL,
    error text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (task_id)
);

-- ===== tianshu.scheduled_tasks =====
CREATE TABLE tianshu.scheduled_tasks (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    thread_id varchar(64),
    context_mode varchar(32) NOT NULL,
    assistant_id varchar(128),
    title varchar(255) NOT NULL,
    prompt text NOT NULL,
    schedule_type varchar(16) NOT NULL,
    schedule_spec json NOT NULL,
    timezone varchar(64) NOT NULL,
    status varchar(16) NOT NULL,
    overlap_policy varchar(16) NOT NULL,
    next_run_at timestamptz,
    last_run_at timestamptz,
    last_run_id varchar(64),
    last_thread_id varchar(64),
    last_error text,
    lease_owner varchar(128),
    lease_expires_at timestamptz,
    run_count numeric(32,0) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);

-- ===== tianshu.store =====
CREATE TABLE tianshu.store (
    prefix text NOT NULL,
    key text NOT NULL,
    value jsonb NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz,
    ttl_minutes numeric(32,0),
    PRIMARY KEY (prefix, key)
);

-- ===== tianshu.store_migrations =====
CREATE TABLE tianshu.store_migrations (
    v numeric(32,0) NOT NULL,
    PRIMARY KEY (v)
);

-- ===== tianshu.threads_meta =====
CREATE TABLE tianshu.threads_meta (
    thread_id varchar(64) NOT NULL,
    assistant_id varchar(128),
    user_id varchar(64),
    display_name varchar(256),
    status varchar(20) NOT NULL,
    metadata_json json NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (thread_id)
);

-- ===== tianshu.user_mcp =====
CREATE TABLE tianshu.user_mcp (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    display_name varchar(255),
    description text,
    transport varchar(16) NOT NULL,
    command varchar(1024),
    args json,
    env json,
    url varchar(2048),
    tool_name_prefix boolean NOT NULL,
    tool_call_timeout double precision,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, name)
);

-- ===== tianshu.user_models =====
CREATE TABLE tianshu.user_models (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    display_name varchar(256),
    description text,
    provider varchar(32) NOT NULL,
    api_key text,
    base_url varchar(512),
    model varchar(256) NOT NULL,
    parameters json NOT NULL,
    supports_thinking boolean NOT NULL,
    supports_reasoning_effort boolean NOT NULL,
    context_window numeric(32,0),
    enabled boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, name)
);

-- ===== tianshu.user_settings =====
CREATE TABLE tianshu.user_settings (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    key varchar(64) NOT NULL,
    value json NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, key)
);

-- ===== tianshu.user_workspaces =====
CREATE TABLE tianshu.user_workspaces (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, name)
);

-- ===== tianshu.users =====
CREATE TABLE tianshu.users (
    id varchar(36) NOT NULL,
    email varchar(320) NOT NULL,
    password_hash varchar(128),
    system_role varchar(16) NOT NULL,
    created_at timestamptz NOT NULL,
    oauth_provider varchar(32),
    oauth_id varchar(128),
    needs_setup boolean NOT NULL,
    token_version numeric(32,0) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (oauth_provider, oauth_id),
    UNIQUE (email)
);

-- ===== tianshu.webhook_deliveries =====
CREATE TABLE tianshu.webhook_deliveries (
    channel varchar(64) NOT NULL,
    workspace_id varchar(512) NOT NULL,
    chat_id varchar(512) NOT NULL,
    message_id varchar(1024) NOT NULL,
    first_seen timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (channel, workspace_id, chat_id, message_id)
);

-- ===== tianshu.workflow_edges =====
CREATE TABLE tianshu.workflow_edges (
    id varchar(64) NOT NULL,
    workflow_id varchar(64) NOT NULL,
    source_node_id varchar(64) NOT NULL,
    target_node_id varchar(64) NOT NULL,
    label varchar(128) NOT NULL,
    sort_order numeric(32,0) NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (source_node_id) REFERENCES tianshu.workflow_edges(id),
    FOREIGN KEY (target_node_id) REFERENCES tianshu.workflow_edges(id),
    FOREIGN KEY (workflow_id) REFERENCES tianshu.workflow_edges(id)
);

-- ===== tianshu.workflow_execution_steps =====
CREATE TABLE tianshu.workflow_execution_steps (
    id varchar(64) NOT NULL,
    execution_id varchar(64) NOT NULL,
    node_id varchar(64) NOT NULL,
    status varchar(32) NOT NULL,
    input_data json,
    output_data json,
    error_message text NOT NULL,
    duration_ms numeric(32,0) NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    PRIMARY KEY (id),
    FOREIGN KEY (execution_id) REFERENCES tianshu.workflow_execution_steps(id),
    FOREIGN KEY (node_id) REFERENCES tianshu.workflow_execution_steps(id)
);

-- ===== tianshu.workflow_executions =====
CREATE TABLE tianshu.workflow_executions (
    id varchar(64) NOT NULL,
    workflow_id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    status varchar(32) NOT NULL,
    inputs json NOT NULL,
    outputs json,
    error_message text NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    PRIMARY KEY (id),
    FOREIGN KEY (workflow_id) REFERENCES tianshu.workflow_executions(id)
);

-- ===== tianshu.workflow_nodes =====
CREATE TABLE tianshu.workflow_nodes (
    id varchar(64) NOT NULL,
    workflow_id varchar(64) NOT NULL,
    node_type varchar(32) NOT NULL,
    name varchar(256) NOT NULL,
    config json NOT NULL,
    input_mapping json NOT NULL,
    position_x numeric(32,0) NOT NULL,
    position_y numeric(32,0) NOT NULL,
    sort_order numeric(32,0) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (workflow_id) REFERENCES tianshu.workflow_nodes(id)
);

-- ===== tianshu.workflows =====
CREATE TABLE tianshu.workflows (
    id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(256) NOT NULL,
    description text NOT NULL,
    definition json NOT NULL,
    input_schema json NOT NULL,
    output_schema json,
    is_template boolean NOT NULL,
    version numeric(32,0) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id)
);

-- ===== tianshu.workspace_files =====
CREATE TABLE tianshu.workspace_files (
    id varchar(64) NOT NULL,
    folder_id varchar(64) NOT NULL,
    workspace_id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(255) NOT NULL,
    extension varchar(20),
    mime_type varchar(120),
    size_bytes numeric(64,0) NOT NULL DEFAULT '0'::bigint,
    content text,
    storage_status varchar(20) NOT NULL DEFAULT 'embedded'::character varying,
    content_ref varchar(512),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (folder_id, name)
);

-- ===== tianshu.workspace_folders =====
CREATE TABLE tianshu.workspace_folders (
    id varchar(64) NOT NULL,
    workspace_id varchar(64) NOT NULL,
    user_id varchar(64) NOT NULL,
    name varchar(100) NOT NULL,
    sort_order numeric(32,0) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    git_provider varchar(16),
    git_repo_url varchar(2048),
    git_repo_name varchar(255),
    git_updated_at timestamptz,
    PRIMARY KEY (id),
    UNIQUE (workspace_id, name)
);
